# Read this first
# https://github.com/sasstools/sass-lint/tree/master#rules

# Linter Options
options:
  merge-default-rules: false
  max-warnings: 50

# File Options
files:
  include: 'src/**/*.s+(a|c)ss'

# Rule Configuration
rules:
  attribute-quotes:
  - 2
  -
    include: true
  bem-depth:
  - 2
  -
    max-depth: 3
  border-zero:
  - 2
  -
    convention: none
  brace-style:
  - 2
  -
    style: 1tbs
    allow-single-line: false
  class-name-format:
  - 2
  -
    convention: hyphenatedbem
  final-newline: 2
  function-name-format:
    - 2
    -
      convention: camelcase
  extends-before-mixins: 2
  extends-before-declarations: 2
  hex-length: 0
  hex-notation:
    - 2
    -
      style: lowercase
  indentation:
    - 2
    -
      size: 2
  leading-zero:
    - 2
    - include: false
  mixin-name-format:
    - 2
    -
      convention: camelcase
      allow-leading-underscore: false
  mixins-before-declarations:
    - true
    -
      exclude: ['bpMinXSmall','bpMinSmall','bpMinMedium','bpMinLarge']
  nesting-depth:
    - 2
    -
      max-depth: 3
  no-color-keywords: 0
  no-css-comments: 1
  no-ids: 2
  no-important: 2
  no-mergeable-selectors: 2
  one-declaration-per-line: 2
  placeholder-name-format: 0
  placeholder-in-extend: 2
  property-sort-order:
    - 2
    -
      ignore-custom-properties: false
  space-between-parens: 2
  space-before-colon: 2
  space-before-brace: 2
  space-around-operator: 2
  space-after-comma: 2
  space-after-colon: 2
  trailing-semicolon: 2
  url-quotes: 2
  variable-name-format: 0
  zero-unit: 2
