language: node_js
node_js:
  - "7"
cache:
  directories:
    - "node_modules"
script:
  - node_modules/.bin/gulp lint
deploy:
  skip_cleanup: true
  provider: script
  script: node_modules/.bin/gulp deploy
notifications:
  email: false
