language: node_js
node_js:
  - "lts/*"
cache: npm
before_script:
  - npm install -g gulp-cli
script:
  - gulp lint
before_deploy: gulp build
deploy:
  skip_cleanup: true
  provider: surge
  project: ./www/
  domain: https://tgc-fractal.surge.sh
notifications:
  email: false
