language: node_js
node_js:
  - "lts/*"
cache: npm
before_script:
  - npm install -g gulp-cli
script:
  - gulp lint
deploy:
  skip_cleanup: true
  provider: script
  script: gulp deploy
notifications:
  email: false
