module.exports = {
  title: "Icons",
  label: "Icons",
  status: "ready",
  default: "all",
  context: {
    icons: [
      "tgc-logo-long",
      "tgc-logo-long-themed",
      "tgc-logo-long-outline",
      "tgc-logo-long-outline-themed",
      "tgc-logo-long-no-ring",
      "tgc-logo-long-no-ring-themed",
      "fiec-themed",
      "comission-themed",
      "conversation",
      "download",
      "listen",
      "subscribe",
      "map",
      "bible",
      "email",
      "clock",
      "calendar",
      "person",
      "christianity-explored",
      "one21",
      "video",
    ],
  },
  variants: [
    {
      name: "all",
      label: "All",
    },
  ],
};
